#!/bin/sh

gem build luna_scanner.gemspec

cd vendor/cache
gem install --no-ri --no-rdoc  --local net-ssh-2.7.0.gem
gem install --no-ri --no-rdoc  --local net-scp-1.1.2.gem
gem install --no-ri --no-rdoc  --local rack-1.5.2.gem
gem install --no-ri --no-rdoc  --local rack-protection-1.5.1.gem
gem install --no-ri --no-rdoc  --local rake-10.1.0.gem
gem install --no-ri --no-rdoc  --local sinatra-1.4.4.gem
gem install --no-ri --no-rdoc  --local tilt-1.4.1.gem
gem install --no-ri --no-rdoc  --local tilt-1.4.1.gem

echo "Installed dependency."

cd ../..
gem install --no-ri --no-rdoc --local luna_scanner-0.0.2.gem